src/Entity/EvenementParticiper.php
<?php

namespace App\Entity;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EvenementParticiperRepository")
 */
class EvenementParticiper
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre;
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $img_event_part;
    
    private $image;
    
    
    public function getId(): ?int
    {
        return $this->id;
    }
    public function setId(int $id): self
    {
        $this->id=$id;
        
        return $this;
    }
    
    public function getTitre(): ?string
    {
        return $this->titre;
    }
    
    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;
        
        return $this;
    }
    
    public function getDescription(): ?string
    {
        return $this->description;
    }
    
    public function setDescription(?string $description): self
    {
        $this->description = $description;
        
        return $this;
    }
    
    
    public function getImage()
    {
        return $this->image;
    }
    
    
    
    public function getImgEventPart(): ?string
    {
        return $this->img_event_part;
    }
    public function setImgEventPart(string $img_event_part): self
    {
        $this->img_event_part = $img_event_part;
        return $this;
    }
    
    /**
     *
     * @param UploadedFile $Image
     * @return \App\Entity\EvenementParticiper
     */
    public function setImage(UploadedFile $Image=null)
    {
        $this->image=$Image;
        
    }
}

templates/site/accueil.html.twig
{% extends 'base.html.twig' %}

{% block section %}

		
		
        <div class="col-xl-10 col-lg-10 col-md-9 col-sm-12">
		<section class="container-fluid" >
		<div class="row justifiy-content-center">
			<div class="col-xl-10 col-lg-10 col-md-12 col-sm-12">
            {% for article in tableauObjetArticle %}
            <aside class="container-fluid" id="article1">
				<div class="row" id="paragrapheDescription1">
					{% if article.imgArticle %}
					<div class="col-12 ">
					{% else %}
					<div class="col-12 text-left ">
					{% endif %}
						<h1 class="mt-2 mb-3">{{ article.titre }}</h1>
						{% if article.sousTitre %}
							<h2 class="mt-4 mb-3">{% include template_from_string(article.sousTitre) %}</h2>
						    {% endif %}
					    {% if article.imgArticle %}
					    <div class="row">
						<div class="col-xl-8 col-lg-8 col-md-7 col-sm-12 col-12 text-left">
					    {% endif %}
                            
							<p class="mb-0">{% include template_from_string(article.description) %}</p>
					    {% if article.imgArticle %}
						</div>
						<div class="col-xl-4 col-lg-4 col-md-5 col-sm-12 col-12">
							<!-- <a href="http://www.angletaccueille.com/">--><img class="img-fluid rounded border border-light" src="{{ absolute_url(asset('img/article/' ~ article.imgArticle))}}" alt="{{ article.titre }}"/><!-- </a>-->
						</div>
						</div>
					    {% endif %}
					</div>
				</div>
			</aside>
                   
            
            {% endfor %}
			</div>
			<div class="col-xl-2 col-lg-2 col-md-12 col-sm-12">
			</div>
		</div>
		</section>
		</div>
		
{% endblock %}

templates/site/activite.html.twig
{% extends 'base.html.twig' %}

{% block section %}

		<div class="col-xl-10 col-lg-10 col-md-9 col-sm-12">
		
		<section class="container-fluid" id="sectionActivite">
        <div class="row justifiy-content-center">
			<div class="col-xl-10 col-lg-10 col-md-12 col-sm-12">
			<h1 class="font-weight-bold font-italic text-center">Nos Activit&eacute;s</h1>
			{% if listeJeu %}
			<aside class="container-fluid my-3" id="asideJdr">
			<div class="row justify-content-center">
				<h1 class="col-12 text-left my-4">Les diff&eacute;rents jeux de r&ocirc;les propos&eacute;s :</h1>
				 	<div class="col-12">
				 	<div class="row">
					{% for jeu in listeJeu %}
						<div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12 mx-0 my-2" id="accordion">
							<div class="card-deck col-12 mx-0">
								<div class="card bg-light border-dark">
								<!-- <img src="/lalegionduphenix/img/jdr/anima.jpg" id="imgJdr"/>-->
									<img class="card-img-top" src="{{ absolute_url(asset('img/jdr/' ~ jeu.imgJeu))}}" alt='{{ jeu.titre}}' id="imgJdr"/>
									<div class="card-header border border-light rounded" id="boutonDeroulantCarte">
										<h5 class="mb-0 text-center">
											<button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ jeu.id }}" aria-expanded="false" aria-controles="collapse{{ jeu.id }}">
												{{jeu.titre}}
											</button>
										</h5>
									</div>
									<div id="collapse{{ jeu.id() }}" class="collapse" aria-labelledby="boutonDeroulantCarte" data-parent="#accordion">			
										<div class="card-body" id="paragrapheDescription">
											<p class="card-text">{{ jeu.description}}</p>
										</div>
									</div>	
								</div>
							</div>	
						</div>
					
					{% endfor %}
					
					
					</div>
					</div>
				</div>			
			</aside>
			{% endif %}
			{% if listeEventOrga %}
			<aside class="container-fluid my-3" id="asideJdr">
			<div class="row justify-content-center">
				<h1 class="col-12 text-left my-4">Les diff&eacute;rents &eacute;v&egrave;nements Organis&eacute;s par nos soins</h1>
				 	<div class="col-12">
				 	<div class="row">
					{% for eventOrga in listeEventOrga %}
						<div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12 mx-0 my-2" id="accordion">
							<div class="card-deck col-12 mx-0">
								<div class="card bg-light border-dark">
								<!-- <img src="/lalegionduphenix/img/jdr/anima.jpg" id="imgJdr"/>-->
									<img class="card-img-top" src="{{ absolute_url(asset('img/eventOrganise/' ~ eventOrga.imgEventOrga))}}" alt='{{ eventOrga.titre}}' id="imgJdr"/>
									<div class="card-header border border-light rounded" id="boutonDeroulantCarte">
										<h5 class="mb-0 text-center">
											<button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ eventOrga.id }}" aria-expanded="false" aria-controles="collapse{{ eventOrga.id() }}">
												{{eventOrga.titre}}
											</button>
										</h5>
									</div>
									<div id="collapse{{ eventOrga.id }}" class="collapse" aria-labelledby="boutonDeroulantCarte" data-parent="#accordion">			
										<div class="card-body" id="paragrapheDescription">
											<p class="card-text">{{ eventOrga.description}}</p>
										</div>
									</div>	
								</div>
							</div>	
						</div>
					
					{% endfor %}
					
					
					</div>
					</div>
				</div>			
			</aside>
			{% endif %}
			{% if listeEventPart %}
			<aside class="container-fluid my-3" id="asideJdr">
			<div class="row justify-content-center">
				<h1 class="col-12 text-left my-4">Les diff&eacute;rents &eacute;v&egrave;nements auquels nous participons :</h1>
				 	<div class="col-12">
				 	<div class="row">
					{% for eventPart in listeEventPart %}
						<div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12 mx-0 my-2" id="accordion">
							<div class="card-deck col-12 mx-0">
								<div class="card bg-light border-dark">
								<!-- <img src="/lalegionduphenix/img/jdr/anima.jpg" id="imgJdr"/>-->
									<img class="card-img-top" src="{{ absolute_url(asset('img/evenementParticiper/' ~ eventPart.imgEventPart))}}" alt='{{ eventPart.titre}}' id="imgJdr"/>
									<div class="card-header border border-light rounded" id="boutonDeroulantCarte">
										<h5 class="mb-0 text-center">
											<button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ eventPart.id }}" aria-expanded="false" aria-controles="collapse{{ eventPart.id }}">
												{{eventPart.titre}}
											</button>
										</h5>
									</div>
									<div id="collapse{{ eventPart.id }}" class="collapse" aria-labelledby="boutonDeroulantCarte" data-parent="#accordion">			
										<div class="card-body" id="paragrapheDescription">
											<p class="card-text">{{ eventPart.description}}</p>
										</div>
									</div>	
								</div>
							</div>	
						</div>
					
					{% endfor %}
					
					
					</div>
					</div>
				</div>			
			</aside>
			{% endif %}
			</div>
			<div class="col-xl-2 col-lg-2 col-md-12 col-sm-12">
			</div>
		</div>
		</section>
		</div>
{% endblock %}

templates/site/contact.html.twig
{% extends 'base.html.twig' %}

{% block section %}
		
    	
		<div class="col-xl-10 col-lg-10 col-md-9 col-sm-12">
		<section class="container-fluid" id="sectionContact">
		     
        <div class="row justifiy-content-center">
			<div class="col-xl-10 col-lg-10 col-md-12 col-sm-12">
			<h1 class="font-weight-bold font-italic text-center">Nous Contacter</h1>   
			<div class="row">
				<div class="col-12">
			<aside class="container-fluid" id="coordonnee">
				{% for lieu in tableauLieu %}
				<div class="row justifiy-content-center my-3">
					<div class="col-12">
						<div class="row" id="paragrapheDescriptionContact">
						<h1 class="col-12 mt-2 mb-3">*<a href="{{ lieu.urlSite }}">{{ lieu.nom }}</a>:</h1>
							<div class="col-xl-8 col-lg-8 col-md-7 col-sm-12 col-12 text-center">
								<p class="mb-0">{{ lieu.adresse }}</p>
								<p class="mb-0">{{ lieu.codePostal }} - {{ lieu.ville }}</p>
								<p class="mb-0">Horaires d'ouverture: {{ lieu.heureDebut }}h-{{ lieu.heureFin }}h</p>
								<p class="mb-0">Contact t&eacute;l&eacute;phone: {{ lieu.telephone }}</p>
								<p class="mb-0">Pour acceder &agrave; notre forum, cliquez <a href="http://lalegionduphenix.forumprod.com">ici</a></p>					
							</div>
							<div class="col-xl-4 col-lg-4 col-md-5 col-sm-12 col-12">
								<a href="{{ lieu.urlSite }}"><img class="img-fluid rounded" src="{{ absolute_url(asset("/img/lieu/" ~ lieu.imgLieu)) }}" id="Mpd"/></a>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
			</aside>
			</div>			
			<div class="col-12">
			<aside class="container-fluid " id="carteGoogle">
				<div class="map-responsive" id="affichageCarte">
					
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2047.0223731116482!2d-1.514303420961198!3d43.48299792972747!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd5140052eef8f15%3A0xc2e89d48d574293e!2s6+Rue+Albert+le+Barillier%2C+64600+Anglet!5e0!3m2!1sfr!2sfr!4v1534453047568" width="800" height="600" frameborder="0" style="border:0" id="carteIframe" allowfullscreen></iframe>				
					
				</div>
			</aside>
			</div>
			<div class="col-12 my-4">
			<aside class="container-fluid" id="asideFormulaireContact">
				<div class="row justify-content-center" id="contactForm">
    				{{ form_start(formContact,{'attr':{'novalidate':'novalidate','role':'form'}})}}
						<div class="form-row my-2 mx-0">
							<div class="form-group col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 px-0">
								<div class="row mx-0">
							        {{ form_widget(formContact.nomUtilisateur) }}
							    </div>
							</div>
							<div class="form-group col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 px-0">
								<div class="row mx-0">
							        {{ form_widget(formContact.prenomUtilisateur) }}
							    </div>
							</div>
							<div class="form-group col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 px-0">
								<div class="row mx-0">
							        {{ form_widget(formContact.telephone) }}
							    </div>
							</div>
							<div class="form-group col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 px-0">
								<div class="row mx-0">
							        {{ form_widget(formContact.mail) }}
							    </div>
							</div>
							<div class="form-group col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 px-0">
								<div class="row mx-0">
							        {{ form_widget(formContact.sujet) }}
							    </div>
							</div>
							<div class="form-group col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 px-0">
								<div class="row mx-0">
							        {{ form_widget(formContact.message) }}
							    </div>
							</div>
							
						</div>
												
						<button class='btn btn-primary col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 mr-2 mb-1' type="submit">Valider</button>
							
						
						{{ form_end(formContact) }}
				</div>
			</aside>
			</div>
			</div>
			</div>
			<div class="col-xl-2 col-lg-2 col-md-12 col-sm-12">
			</div>
		</div>
		</section>
		</div>
{% endblock %}

templates/site/tarif.html.twig
{% extends 'base.html.twig' %}

{% block section %}

		<div class="col-xl-10 col-lg-10 col-md-9 col-sm-12 ">
		
		<section class="container-fluid " >
		
        <div class="row justifiy-content-center ">
			<div class="col-xl-10 col-lg-10 col-md-12 col-sm-12 ">
			<h1 class="text-center">Nos Formules et Informations diverses</h1>
			<aside class="container-fluid">
				<div class="row">
				<div class="col-12" id="paragrapheDescriptionTarif">
					
					<h2 class="mt-2 mb-3">Nos tarifs:</h2>
					{% for info in infoTableau %}
						<p class="mb-0">- Notre cotisation annuelle s'&eacute;l&egrave;ve &agrave; <strong>{{ info.tarif }}&euro;</strong> pour l'acc&egrave;s &agrave; tous nos locaux.</p>
						<p class="mb-0">- Toute personne d&eacute;sireuse de tester nos activit&eacute;s disposera de <strong>{{ info.seance_essai }} s&eacute;ances d'essais</strong>.</p>
					{% endfor %}
					</div>
				</div>
				<div class="row">
				<div class="col-12" id="paragrapheDescriptionTarif">
					<h2 class="mt-4 mb-3">Les pr&eacute;-requis pour s'inscrire:</h2>
						<p class="mb-0">- Toute personne souhaitant s'inscrire dans notre association, devra au minimum avoir 15 ans r&eacute;volus.</p>
				</div>
				</div>
				<div class="row">
				<div class="col-12" id="paragrapheDescriptionTarif">
					<h2 class="mt-4 mb-3">Nos documents utiles:</h2>
						<div class="col table-responsive">
						<table class="table table-secondary table-striped table-bordered table-hover table-sm">
							<thead>
								<tr>
									<th>Fichiers a t&eacute;l&eacute;charger</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
							
							{% for fichier in objetFichier %}
								
								
								<tr>
									<td>{{fichier.nomAffichage }}</td>	
									<td><a href="{{absolute_url(asset('doc/' ~ fichier.nomFichier))}}">T&eacute;l&eacute;charger</a></td>															
								</tr>
							{% endfor %}
								
							</tbody>
						</table>
					</div>
				</div>
				</div>
				</div>
			</aside>
			</div>
			<div class="col-xl-2 col-lg-2 col-md-12 col-sm-12 ">
			</div>
		</div>
		</section>
		</div>
		
{% endblock %}